/**
 * GENERATED BY BIMM-AGENT
 * File: src/components/AddCarForm.tsx
 * Task: Develop the AddCarForm component with MUI Dialog t...
 */

import { useState } from "react";
import { useMutation } from "@apollo/client";
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, TextField } from "@mui/material";
import { ADD_CAR, GET_CARS } from "@/graphql/operations";

export default function AddCarForm() {
  const [open, setOpen] = useState(false);
  const [make, setMake] = useState("");
  const [model, setModel] = useState("");
  const [year, setYear] = useState<number | "">("");
  const [color, setColor] = useState("");

  const [addCar] = useMutation(ADD_CAR, {
    refetchQueries: [{ query: GET_CARS }],
  });

  const handleClickOpen = () => {
    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
  };

  const handleAddCar = () => {
    if (make && model && year && color) {
      addCar({ variables: { make, model, year: Number(year), color } });
      setMake("");
      setModel("");
      setYear("");
      setColor("");
      handleClose();
    }
  };

  return (
    <>
      <Button variant="outlined" onClick={handleClickOpen}>
        Add New Car
      </Button>
      <Dialog open={open} onClose={handleClose}>
        <DialogTitle>Add a New Car</DialogTitle>
        <DialogContent>
          <TextField
            autoFocus
            margin="dense"
            label="Make"
            type="text"
            fullWidth
            variant="outlined"
            value={make}
            onChange={(e) => setMake(e.target.value)}
          />
          <TextField
            margin="dense"
            label="Model"
            type="text"
            fullWidth
            variant="outlined"
            value={model}
            onChange={(e) => setModel(e.target.value)}
          />
          <TextField
            margin="dense"
            label="Year"
            type="number"
            fullWidth
            variant="outlined"
            value={year}
            onChange={(e) => setYear(e.target.value ? Number(e.target.value) : "")}
          />
          <TextField
            margin="dense"
            label="Color"
            type="text"
            fullWidth
            variant="outlined"
            value={color}
            onChange={(e) => setColor(e.target.value)}
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={handleClose} color="secondary">
            Cancel
          </Button>
          <Button onClick={handleAddCar} color="primary">
            Add Car
          </Button>
        </DialogActions>
      </Dialog>
    </>
  );
}