/**
 * GENERATED BY BIMM-AGENT
 * File: src/components/CarCard.tsx
 * Task: Implement a CarCard component that displays car de...
 */

import { Card, CardContent, CardMedia, Typography } from "@mui/material";
import type { Car } from "@/types";

interface CarCardProps {
  car: Car;
}

export default function CarCard({ car }: CarCardProps) {
  return (
    <Card sx={{ mb: 2 }}>
      <CardMedia
        component="img"
        sx={{
          display: { xs: "block", sm: "none" },
        }}
        image={car.mobile}
        alt={`${car.make} ${car.model} Mobile`}
      />
      <CardMedia
        component="img"
        sx={{
          display: { xs: "none", sm: "block", md: "none" },
        }}
        image={car.tablet}
        alt={`${car.make} ${car.model} Tablet`}
      />
      <CardMedia
        component="img"
        sx={{
          display: { xs: "none", md: "block" },
        }}
        image={car.desktop}
        alt={`${car.make} ${car.model} Desktop`}
      />
      <CardContent>
        <Typography variant="h6">
          {car.year} {car.make} {car.model}
        </Typography>
        <Typography color="text.secondary">{car.color}</Typography>
      </CardContent>
    </Card>
  );
}