/**
 * GENERATED BY BIMM-AGENT
 * File: src/components/CarList.tsx
 * Task: Implement CarList to iterate over cars and render ...
 */

import { Grid } from "@mui/material";
import CarCard from "@/components/CarCard";
import type { Car } from "@/types";

interface CarListProps {
  cars: Car[];
  searchTerm: string;
  sortBy: string;
}

export default function CarList({ cars, searchTerm, sortBy }: CarListProps) {
  const filteredCars = cars.filter(car =>
    `${car.make} ${car.model}`.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const sortedCars = [...filteredCars].sort((a, b) => {
    if (sortBy === "year") {
      return a.year - b.year;
    }
    const aValue = a[sortBy as keyof Car];
    const bValue = b[sortBy as keyof Car];
    if (typeof aValue === "string" && typeof bValue === "string") {
      return aValue.localeCompare(bValue);
    }
    return 0;
  });

  return (
    <Grid container spacing={2}>
      {sortedCars.map(car => (
        <Grid item xs={12} sm={6} md={4} key={car.id}>
          <CarCard car={car} />
        </Grid>
      ))}
    </Grid>
  );
}