/**
 * GENERATED BY BIMM-AGENT
 * File: src/components/SearchBar.tsx
 * Task: Create a SearchBar component that receives searchT...
 */

import { TextField } from "@mui/material";

interface SearchBarProps {
  searchTerm: string;
  setSearchTerm: (term: string) => void;
}

export default function SearchBar({ searchTerm, setSearchTerm }: SearchBarProps) {
  const handleSearchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSearchTerm(event.target.value);
  };

  return (
    <TextField
      label="Search"
      variant="outlined"
      fullWidth
      value={searchTerm}
      onChange={handleSearchChange}
      sx={{ mb: 2 }}
    />
  );
}