import OpenAI from "openai";
import { tools } from "./tools.js";
import {
	CODER_SYSTEM_PROMPT,
	FIXER_SYSTEM_PROMPT,
} from "../prompts/coder-prompt.js";
import dotenv from "dotenv";

dotenv.config();

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export const coder = {
	getContext: (): string => {
		const result = tools.runShellCommand(
			"find src -name '*.ts' -o -name '*.tsx'",
		);

		if (!result.success) return "No files created yet.";

		const allFiles = result.output.split("\n").filter(Boolean);
		let fullContext =
			"### CURRENT PROJECT STATE (Use this for type safety and consistency):\n";

		allFiles.forEach((file) => {
			const content = tools.readFile(file);
			fullContext += `\n--- FILE: ${file} ---\n${content}\n`;
		});

		return fullContext;
	},

	generateCode: async (taskDescription: string, filePath: string) => {
		console.log(`\nGenerating code for: ${filePath}...`);

		const projectContext = coder.getContext();

		const response = await openai.chat.completions.create({
			model: "gpt-4o",
			messages: [
				{
					role: "system",
					content: `${CODER_SYSTEM_PROMPT}\n\n${projectContext}`,
				},
				{
					role: "user",
					content: `TARGET FILE: ${filePath}\nTASK: ${taskDescription}`,
				},
			],
			temperature: 0,
		});

		const code = response.choices[0].message.content || "";
		const cleanCode = code.replace(/```typescript|```tsx|```/g, "").trim();
		const aiHeader = `/**\n * GENERATED BY BIMM-AGENT\n * File: ${filePath}\n * Task: ${taskDescription.substring(0, 50)}...\n */\n\n`;
		const finalContent = aiHeader + cleanCode;

		tools.writeFile(filePath, finalContent);
		console.log(`File ${filePath} written successfully.`);
		return cleanCode;
	},

	fixCode: async (filePath: string, errorMessage: string) => {
		console.log(`\nAttempting to fix: ${filePath}...`);

		const brokenCode = tools.readFile(filePath);
		const projectContext = coder.getContext();

		const response = await openai.chat.completions.create({
			model: "gpt-4o",
			messages: [
				{
					role: "system",
					content: `${FIXER_SYSTEM_PROMPT}\n\n${projectContext}`,
				},
				{
					role: "user",
					content: `FILE: ${filePath}\nERROR: ${errorMessage}\n\nCODE TO FIX:\n${brokenCode}`,
				},
			],
			temperature: 0,
		});

		const fixedCode = response.choices[0].message.content || "";
		const cleanCode = fixedCode.replace(/```typescript|```tsx|```/g, "").trim();

		tools.writeFile(filePath, cleanCode);

		return cleanCode;
	},
};
