/**
 * GENERATED BY BIMM-AGENT
 * File: src/App.tsx
 * Task: LIFTING STATE UP: Implement global state for searc...
 */

import { useState } from "react";
import { Container, Typography, Box } from "@mui/material";
import SearchBar from "@/components/SearchBar";
import SortActions from "@/components/SortActions";
import CarList from "@/components/CarList";
import AddCarForm from "@/components/AddCarForm";
import { useQuery } from "@apollo/client";
import { GET_CARS } from "@/graphql/operations";
import type { Car } from "@/types";

export default function App() {
  const { data, loading, error } = useQuery<{ cars: Car[] }>(GET_CARS);
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [sortBy, setSortBy] = useState<string>("");

  if (loading) return <Typography>Loading...</Typography>;
  if (error) return <Typography>Error: {error.message}</Typography>;

  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      <Typography variant="h3" component="h1" gutterBottom>
        Car Inventory Manager
      </Typography>
      <Box sx={{ mb: 2 }}>
        <SearchBar searchTerm={searchTerm} setSearchTerm={setSearchTerm} />
        <SortActions sortBy={sortBy} setSortBy={setSortBy} />
        <AddCarForm />
      </Box>
      <CarList cars={data?.cars || []} searchTerm={searchTerm} sortBy={sortBy} />
    </Container>
  );
}