/**
 * GENERATED BY BIMM-AGENT
 * File: src/types.ts
 * Task: Define the Car interface matching the actual field...
 */

export interface Car {
  id: string;
  make: string;
  model: string;
  year: number;
  color: string;
  mobile: string;
  tablet: string;
  desktop: string;
}