/**
 * GENERATED BY BIMM-AGENT
 * File: src/graphql/operations.ts
 * Task: Define GraphQL queries and mutations for Cars to s...
 */

import { gql } from "@apollo/client";

export const GET_CARS = gql`
  query GetCars {
    cars {
      id
      make
      model
      year
      color
      mobile
      tablet
      desktop
    }
  }
`;

export const GET_CAR = gql`
  query GetCar($id: ID!) {
    car(id: $id) {
      id
      make
      model
      year
      color
      mobile
      tablet
      desktop
    }
  }
`;

export const ADD_CAR = gql`
  mutation AddCar(
    $make: String!
    $model: String!
    $year: Int!
    $color: String!
  ) {
    addCar(make: $make, model: $model, year: $year, color: $color) {
      id
      make
      model
      year
      color
      mobile
      tablet
      desktop
    }
  }
`;

export const GET_SORTED_CARS = gql`
  query GetSortedCars($sortBy: String!) {
    cars(sortBy: $sortBy) {
      id
      make
      model
      year
      color
      mobile
      tablet
      desktop
    }
  }
`;